# Generated by Django 3.2.3 on 2021-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FibonacciNumber', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
